version: 0.1.{build}
image: Visual Studio 2019
init:
- ps: Install-Product node $env:nodejs_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nodejs_version: 11
install:
- cmd: >-
    git submodule sync --recursive

    git submodule update --init --recursive
build_script:
- cmd: >-
    dotnet publish  -c Release   ./IoTSharp/IoTSharp.csproj

    dotnet publish  -c Release    ./IoTSharp.Edge.ModBus/IoTSharp.Edge.ModBus.csproj
artifacts:
- path: IoTSharp\bin\Release\netcoreapp3.0\publish\
  name: IoTSharp
- path: IoTSharp.Extensions\bin\Release\*.nupkg
  name: IoTSharp.Extensions
- path: IoTSharp.Edge.ModBus\bin\Release\netcoreapp3.0\publish\
  name: IoTSharp.Edge.ModBus
deploy: off